routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('master');
});

Route::get('/dashboard', function () {
    return view('master_parts.dashboard');
});

Route::get('/table', function () {
    return view('master_parts.table');
});

Route::get('/data-tables', function () {
    return view('master_parts.data_tables');
});

//CRUD Cast implementation

// //menampilkan form untuk membuat data pemain baru
// Route::get('/cast/create', 'CastController@create')->name("cast_create"); 

// //menyimpan data baru ke tabel cast
// Route::post('/cast', 'CastController@store')->name("cast_store");

// //menampilkan list data para pemain film menggunakan html table
// Route::get('/cast', 'CastController@index')->name("cast_index");

// //menangkap id dari url dan menampilkan casters dengan lebih detail
// Route::get('/cast/{id}', 'CastController@show')->name("cast_show");

// //menangkap id dari url dan menampilkan halaman edit
// Route::get('/cast/{id}/edit', 'CastController@edit')->name("cast_edit");

// //menangkap id dari url dan akan mengupdate data dari caster tersebut
// Route::put('/cast/{id}', 'CastController@update')->name("cast_update");

// //menangkap id dari url dan akan menghapus data caster tersebut dari database
// Route::delete('/cast/{id}', 'CastController@destroy')->name("cast_delete");

Route::resource('cast', 'CastController');

app/Cast.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cast extends Model
{
    protected $table = "cast";
    protected $fillable = ['nama', "umur", "bio"];
      
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CastController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use DB; //pakai database yang telah diatur di file .env

use App\Cast; //pakai file Cast.php di dalam folder app

class CastController extends Controller
{
    public function create(){
        return view('posts.create_cast');
    }

    public function store(Request $request){
        //dd($request->all());

        //validasi data agar sesuai dengan syarat untuk masuk ke database
        $request->validate([
            'Nama' => 'required|unique:cast',
            'Umur' => 'required',
            'Bio' => 'required'
        ]);

        //bagian query builder Laravel
        //pakai method insert() untuk memasukkan/menyimpan data ke database
        // $query = DB::table('cast')->insert([
        //     "nama" => $request["Nama"], 
        //     "umur" => $request["Umur"], 
        //     'bio' => $request['Bio']
        // ]);

        //bagian ORM Laravel (Eloquent) (dengan method save() untuk memasukkan/menyimpan)
        // $cast = new Cast;
        // $cast->nama = $request["Nama"];
        // $cast->umur = $request["Umur"];
        // $cast->bio = $request["Bio"];
        // $cast->save();

        //bagian ORM Laravel (Eloquent) (dengan method create() untuk memasukkan/menyimpan)
        $cast = Cast::create([
            "nama" => $request["Nama"], 
            "umur" => $request["Umur"], 
            'bio' => $request['Bio']
        ]);



        return redirect('/cast')->with('success', 'Berhasil membuat cast');
    }

    public function index(){
        //$listCasts = DB::table('cast')->get(); //pakai query builder method get()
        $listCasts = Cast::all(); //pakai ORM method all()
        return view('posts.index_cast', compact('listCasts'));
    }

    public function show($id){
        // $catchedCaster = DB::table('cast')->where('id', $id)->first(); //pakai query builder method where()
        $catchedCaster = Cast::find($id); //pakai ORM method find() 
        //method find() selalu menggunakan primarykey
        return view('posts.show_cast', compact('catchedCaster'));
    }

    public function edit($id){
        // $catchedCaster = DB::table('cast')->where('id', $id)->first(); //pakai query builder method where()
        $catchedCaster = Cast::find($id); //pakai ORM method find() 
        //method find() selalu menggunakan primarykey
        return view('posts.edit_cast', compact('catchedCaster'));
    }

    public function update($id, Request $request){
        //dd($request);
        $request->validate([
            'Nama' => 'required',
            'Umur' => 'required',
            'Bio' => 'required'
        ]);

        //menggunakan query builder
        // $editedCaster = DB::table('cast')
        // ->where('id', $id)
        // ->update([
        //     'nama' => $request['Nama'], 
        //     'umur' => $request['Umur'], 
        //     'bio' => $request['Bio']
        // ]);

        //menggunakan ORM
        $editedCaster = Cast::where('id', $id)
        ->update([
            'nama' => $request['Nama'], 
            'umur' => $request['Umur'], 
            'bio' => $request['Bio']
        ]);

        return redirect('/cast')->with('success', 'Berhasil update cast');
    }

    public function destroy($id){
        //$query = DB::table('cast')->where('id', $id)->delete(); //pakai query builder

        // $query = Cast::find($id);
        // $query->delete(); //pakai ORM method delete() //method delete dapat menggunakan parameter lain

        $query = Cast::destroy($id); //pakai ORM method delete() //ethod destroy hanya dapat menggunakan primarykey sebagai parameter
        return redirect('/cast');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AdminLTE 3 | Blank Page</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{asset('adminlte/plugins/fontawesome-free/css/all.min.css')}}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('adminlte/dist/css/adminlte.min.css')}}">
    <link rel="stylesheet" href="{{asset('customcolor.css')}}">
  
<script src="{{asset('plugins/datatables/jquery.dataTables.js')}}"></script>
<script src="{{asset('plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>
<script>
  $(function () {
    $("#example1").DataTable();
  });
</script>
<script>  
  function hideAlert(){
      document.getElementById('notif').style.visibility="hidden";
  }
  setTimeout("showAlert()", 1000);
  </script>
</head>
<body class="hold-transition sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">
  
        <!-- Navbar -->
    @include('master_parts.nav')
        <!-- /.Navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    @include('master_parts.brand_logo')
    <!-- /.Brand logo -->
    
    <!-- Sidebar -->
    @include('master_parts.sidebar')
    <!-- /.Sidebar -->

  </aside>
  <!-- /.Main Sidebar Container -->

  <!-- Content Wrapper. Contains page content -->    
  <div class="content-wrapper">
      
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
          @yield('back')
          <div class="row mb-2">
            <div class="col-sm-6">
              <br>
              <h3>@yield('title')</h3>
            </div>
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">Blank Page</li>
              </ol>
            </div>
          </div>
        </div><!-- /.container-fluid -->
      </section>
    <!-- Main content -->
    @include('master_parts.main_content')
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!--footer-->
  @include('master_parts.footer')
  <!--/.footer -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- SweetAlert -->
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<!-- jQuery -->
<script src="{{asset('adminlte/plugins/jquery/jquery.min.js')}}"></script>
<!-- Bootstrap 4 -->
<script src="{{asset('adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('adminlte/dist/js/adminlte.min.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{asset('adminlte/dist/js/demo.js')}}"></script>
@stack('deletenotif')
@stack('successnotif')
@stack('script')
</body>
</html>

resources/views/master_parts/brand_logo.blade.php
<a href="#" class="brand-link">
    <img src="{{asset('adminlte/dist/img/AdminLTELogo.png')}}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
    <span class="brand-text font-weight-light">AdminLTE 3</span>
  </a>

resources/views/master_parts/dashboard.blade.php
@extends('master')

@section('title')
    Selamat Datang!
@endsection

@section('content')
    Help me, I'm under the water!
@endsection


@section('create')
  <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
    <i class="fas fa-minus"></i>
  </button>
  <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
    <i class="fas fa-times"></i>
  </button>
@endsection

resources/views/master_parts/footer.blade.php
<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 3.1.0
    </div>
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
  </footer>

resources/views/master_parts/main_content.blade.php
    <section class="content">

        <!-- Default box -->
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">@yield('subtitle')</h3>
            @yield('successnotif')
            @yield('create')              
          </div>
          <div class="card-body">
            
            @yield('content')
          </div>
          <!-- /.card-body -->
          <div class="card-footer">
            
          </div>
          <!-- /.card-footer-->
        </div>
        <!-- /.card -->
  
      </section>

resources/views/master_parts/nav.blade.php
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

    </ul>
  </nav>
  <!-- /.navbar -->

resources/views/master_parts/sidebar.blade.php
    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
          <div class="image">
            <img src="{{asset('adminlte/dist/img/user2-160x160.jpg')}}" class="img-circle elevation-2" alt="User Image">
          </div>
          <div class="info">
            <a href="#" class="d-block">Ken Dahana</a>
          </div>
        </div>
  

  
        <!-- Sidebar Menu -->
        <nav class="mt-2">
          <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
                 with font-awesome or any other icon font library -->
            <li class="nav-item">
              <a href="/dashboard" class="nav-link">
                <i class="nav-icon fa fa-tachometer-alt"></i>
                <p>
                  Dashboard
                </p>
              </a>
            </li>
          

            <li class="nav-item">
              <a href="/cast" class="nav-link">
                <i class="nav-icon fa fa-users"></i>
                <p>
                  Cast
                </p>
              </a>
            </li>

            <li class="nav-item">
              <a href="/genre" class="nav-link">
                <i class="nav-icon fa fa-users"></i>
                <p>
                  Genre
                </p>
              </a>
            </li>

            <li class="nav-item">
              <a href="#" class="nav-link">
                <i class="nav-icon fas fa-table"></i>
                <p>
                  Tables
                  <i class="fas fa-angle-left right"></i>
                </p>
              </a>
              <ul class="nav nav-treeview">
                <li class="nav-item">
                  <a href="/table" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Table</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="/data-tables" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Data Tables</p>
                  </a>
                </li>
              </ul>
            </li>
        </nav>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->

resources/views/master_parts/table.blade.php
@extends('master')

@section('title')
    Table
@endsection

@section('content')
<table class="table table-bordered">
    <thead>                  
      <tr>
        <th style="width: 10px">#</th>
        <th>Task</th>
        <th>Progress</th>
        <th style="width: 40px">Label</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1.</td>
        <td>Update software</td>
        <td>
          <div class="progress progress-xs">
            <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
          </div>
        </td>
        <td><span class="badge bg-danger">55%</span></td>
      </tr>
      <tr>
        <td>2.</td>
        <td>Clean database</td>
        <td>
          <div class="progress progress-xs">
            <div class="progress-bar bg-warning" style="width: 70%"></div>
          </div>
        </td>
        <td><span class="badge bg-warning">70%</span></td>
      </tr>
      <tr>
        <td>3.</td>
        <td>Cron job running</td>
        <td>
          <div class="progress progress-xs progress-striped active">
            <div class="progress-bar bg-primary" style="width: 30%"></div>
          </div>
        </td>
        <td><span class="badge bg-primary">30%</span></td>
      </tr>
      <tr>
        <td>4.</td>
        <td>Fix and squish bugs</td>
        <td>
          <div class="progress progress-xs progress-striped active">
            <div class="progress-bar bg-success" style="width: 90%"></div>
          </div>
        </td>
        <td><span class="badge bg-success">90%</span></td>
      </tr>
    </tbody>
  </table>
  @endsection

resources/views/posts/create_cast.blade.php
@extends('master')

@section('title')
    Isi Data Pemain Film Baru:
@endsection

@section('subtitle')
    Biodata Pemain:
@endsection

@section('back')
<a href="{{route('cast.index')}}"><button type="button" class="btn btn-primary" ><i class="fa fa-angle-left" aria-hidden="true"></i>
    Back</button></a><br>
@endsection

@section('content')

<div class="card-body">
    
    <form role="{{route('cast.store')}}" action="/cast" method="POST">
        @csrf
        <div class="form-group row">
        <label for="inputNama3" class="col-sm-2 col-form-label">Nama:</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="inputNama3" name="Nama" placeholder="Nama" >
            @error('nama')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        
    </div>
    <div class="form-group row">
        <label for="inputUmur3" class="col-sm-2 col-form-label">Umur</label>
        <div class="col-sm-10">
            <input type="number" class="form-control" id="inputUmur3" name="Umur" placeholder="Umur" >
            @error('umur')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        
    </div>

    <div class="form-group row">
        <label for="inputBio3" class="col-sm-2 col-form-label">Bio</label>
        <div class="col-sm-10">
            <textarea type="textarea" class="form-control" id="inputBio3" name="Bio" placeholder="Bio" rows="5" cols="50"></textarea>
            @error('bio')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        
    </div>

    <button class="btn btn-info"><i class="fa fa-plus add" aria-hidden="true" id="add"></i> Tambahkan</button>
    </form>
</div>

@endsection

resources/views/posts/edit_cast.blade.php
@extends('master')

@section('title')
    Edit Data Pemain Film:
@endsection

@section('subtitle')
    Biodata Pemain:
@endsection

@section('back')
<a href="{{route('cast.index')}}"><button type="button" class="btn btn-primary" ><i class="fa fa-times" aria-hidden="true"></i> Cancel</button></a><br>
@endsection

@section('content')

<div class="card-body">
    
    <form role="form" action="{{route('cast.update', ['cast' => $catchedCaster->id])}}" method="post">
        @csrf
        @method('PUT')
    <div class="form-group row">
        <label for="inputNama3" class="col-sm-2 col-form-label">Nama:</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="inputNama3" name="Nama" value="{{old('nama', $catchedCaster->nama)}}" placeholder="Nama" >
            @error('Nama')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        
        
    </div>
    <div class="form-group row">
        <label for="inputUmur3" class="col-sm-2 col-form-label">Umur</label>
        <div class="col-sm-10">
            <input type="number" class="form-control" id="inputUmur3" name="Umur" value="{{old('umur', $catchedCaster->umur)}}"placeholder="Umur" >
            @error('Umur')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        
    </div>

    <div class="form-group row">
        <label for="inputBio3" class="col-sm-2 col-form-label">Bio</label>
        <div class="col-sm-10">
            <textarea class="form-control" id="inputBio3" name="Bio" placeholder="Bio" rows="5" cols="50">{{old('bio', $catchedCaster->bio)}}</textarea>
            @error('Bio')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        
    </div>

    <button type="submit" class="btn btn-info add"><i class="fa fa-check" aria-hidden="true" id="add"></i> Tambahkan</button>
    </form>
</div>

@endsection

resources/views/posts/index_cast.blade.php
@extends('master')

@section('title')
    Daftar pemain:
@endsection

@section('create')
<a href="{{route('cast.create')}}" style="float: right"><button type="button" class="btn btn-primary mt-1 mb-2" ><i class="fa fa-plus" aria-hidden="true"></i>
    Add Caster</button></a>
@endsection

@section('successnotif')
@if(session('success'))
<script>
    function hideAlert(){
        document.getElementById('notif').style.visibility="hidden";
    }
    setTimeout("hideAlert()", 2000);
</script>
    <div class="alert alert-success mb-0" id="notif" style="float: left; width:85%;">
        {{session('success')}}
    </div>
@endif

@endsection

@section('content')
    <table>
    @if (!empty($listCasts[0]))
        <tr>
            <th>ID</th>
            <th>Nama</th>
            <th>Actions</th>
        </tr>
        @foreach ($listCasts as $indexArr => $cast)
        <tr>
            <td>{{$indexArr + 1}}</td>
            <td>{{$cast->nama}}</td>
            <td>
            <a href="{{route('cast.show', ['cast' => $cast->id])}}"><button type="button" style="float: left;" class="btn btn-primary buttonShow mx-1" >Show</button></a>
            <a href="{{route('cast.edit', ['cast' => $cast->id])}}"><button type="button" style="float: left;" class="btn buttonEdit mx-1" >Edit</button></a>   
                <form action="{{route('cast.destroy', ['cast' => $cast->id])}}" method="post" id="">
                    @csrf
                    @method('delete')
                    <input value="Delete" type="submit" style="float: left;" class="btn btn-danger mx-1 btn-delete" id="delete">
                </form>
            </td>
        </tr> 
        @endforeach     
    @else
        <center><h3 colspan="3">NO DATA!</h3> </center>
    @endif
      
    </table>
@endsection

@push('deletenotif')
<script>
$(".btn-delete").on('click', function(e){
    e.preventDefault();
    var parent = document.getElementById("delete").parentElement;
    swal({
        title: "Are you sure?",
        text: "Once deleted, you will not be able to recover this imaginary file!",
        icon: "warning",
        buttons: true,
        dangerMode: true,
        })
        .then((willDelete) => {
            if (willDelete) {
                setTimeout(function deleteFile(){
                parent.submit();
            }, 1500);
            swal("Poof! Your imaginary file has been deleted!", {
            icon: "success",
            });
            }
        });
});
</script>
@endpush

@push('successnotif')
    @if ((session('success')))
    <script>
    swal({
        title: "Changed!",
        text: "{{session('success')}}",
        icon: "success",
        button: "OK",
      });
    </script>
    @endif
@endpush

resources/views/posts/show_cast.blade.php
@extends('master')

@section('back')
<a href="{{route('cast.index')}}"><button type="button" class="btn btn-primary" ><i class="fa fa-angle-left" aria-hidden="true"></i>
    Back</button></a><br>
@endsection

@section('content')

<h3>Biodata:</h3>
<table>
    <tr>
        <td>Data</td>
        <td>Keterangan</td>
    </tr> 
    <tr>
        
        <td>ID</td>
        <td>{{$catchedCaster->id}}</td>
    </tr> 
    <tr>

        <td>Nama</td>
        <td>{{$catchedCaster->nama}}</td>
    </tr> 
    <tr>

        <td>Umur</td>
        <td>{{$catchedCaster->umur}}</td>
    </tr> 
    <tr>

        <td>Bio</td>
        <td>{{$catchedCaster->bio}}</td>
    </tr> 
</table>
@endsection